/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package firetools;

import clone.InfoEntity;
import clone.LogicaDrivers;
import clone.LogicaDriversInterfaz;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.concurrent.CompletableFuture;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
/**
 *
 * @author elcue
 */
public class FireTools extends javax.swing.JFrame {
    //private final AdbManagement adb;
    /**
     * Creates new form FireTools
     */
     private final LogicaDrivers driver;
    public FireTools() {
        //adb = new AdbManagment();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        int y = (int) size.getHeight();
        int x = (int) size.getWidth();
            
        setLocation((x/2)/2-130, (y/2)/2-100);
        ImageIcon icon= new ImageIcon(getClass().getResource("resources\\fireico.ico"));
        setIconImage(icon.getImage());            
        
        initComponents();
        pasosDepuracion();
        driver = new LogicaDriversInterfaz(jProgressBar1, console);
      
        jProgressBar1.setMinimum(0);
        jProgressBar1.setMaximum(100);
        jProgressBar1.setValue(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPasswordField1 = new javax.swing.JPasswordField();
        mainPanel = new javax.swing.JPanel();
        consolepanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        info = new javax.swing.JButton();
        gplay = new javax.swing.JButton();
        social_apps = new javax.swing.JButton();
        uninstall_G = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(253, 169, 30));

        consolepanel.setBackground(new java.awt.Color(102, 102, 102));

        console.setEditable(false);
        console.setBackground(new java.awt.Color(204, 204, 204));
        console.setColumns(20);
        console.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        console.setRows(5);
        jScrollPane1.setViewportView(console);
        console.getAccessibleContext().setAccessibleParent(console);

        javax.swing.GroupLayout consolepanelLayout = new javax.swing.GroupLayout(consolepanel);
        consolepanel.setLayout(consolepanelLayout);
        consolepanelLayout.setHorizontalGroup(
            consolepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        consolepanelLayout.setVerticalGroup(
            consolepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consolepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );

        info.setBackground(new java.awt.Color(26, 12, 90));
        info.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        info.setForeground(new java.awt.Color(255, 255, 255));
        info.setText("Info");
        info.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(51, 255, 255), new java.awt.Color(255, 102, 255), new java.awt.Color(204, 255, 0)));
        info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoMouseEntered(evt);
            }
        });
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });

        gplay.setBackground(new java.awt.Color(26, 12, 90));
        gplay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gplay.setForeground(new java.awt.Color(255, 255, 255));
        gplay.setText("GPlay Store");
        gplay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(51, 255, 255), new java.awt.Color(255, 102, 255), new java.awt.Color(204, 255, 0)));
        gplay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gplayMouseEntered(evt);
            }
        });
        gplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gplayActionPerformed(evt);
            }
        });

        social_apps.setBackground(new java.awt.Color(26, 12, 90));
        social_apps.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        social_apps.setForeground(new java.awt.Color(255, 255, 255));
        social_apps.setText("Social Apps");
        social_apps.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(51, 255, 255), new java.awt.Color(255, 102, 255), new java.awt.Color(204, 255, 0)));
        social_apps.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        social_apps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                social_appsMouseEntered(evt);
            }
        });
        social_apps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                social_appsActionPerformed(evt);
            }
        });

        uninstall_G.setBackground(new java.awt.Color(26, 12, 90));
        uninstall_G.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uninstall_G.setForeground(new java.awt.Color(255, 255, 255));
        uninstall_G.setText("Remove GAPP");
        uninstall_G.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(51, 255, 255), new java.awt.Color(255, 102, 255), new java.awt.Color(204, 255, 0)));
        uninstall_G.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uninstall_G.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uninstall_GMouseEntered(evt);
            }
        });
        uninstall_G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uninstall_GActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\elcue\\OneDrive\\Escritorio\\Projectos\\FireTools\\src\\firetools\\resources\\amazonlabel.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("iCodigo Desbloqueo RD, Revolucionando el mundo del unlocking!!");

        jProgressBar1.setBackground(new java.awt.Color(204, 204, 255));
        jProgressBar1.setForeground(new java.awt.Color(0, 102, 102));
        jProgressBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jProgressBar1.setFocusCycleRoot(true);
        jProgressBar1.setInheritsPopupMenu(true);
        jProgressBar1.setStringPainted(true);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("by iCodigo");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(consolepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gplay, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(social_apps, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uninstall_G, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info)
                    .addComponent(gplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(social_apps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uninstall_G, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addComponent(consolepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uninstall_GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uninstall_GActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uninstall_GActionPerformed

    private void uninstall_GMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uninstall_GMouseEntered
        // TODO add your handling code here:
        this.uninstall_G.setToolTipText("Remueve play store.");

    }//GEN-LAST:event_uninstall_GMouseEntered

    private void social_appsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_social_appsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_social_appsActionPerformed

    private void social_appsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_social_appsMouseEntered
        // TODO add your handling code here:
        this.social_apps.setToolTipText("Instala aplicaciones sociales.");
    }//GEN-LAST:event_social_appsMouseEntered

    private void gplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gplayActionPerformed
        // TODO add your handling code here:
        this.jProgressBar1.setValue(30);
        this.console.append("Buscando dispositivo...");
        CompletableFuture.runAsync(() ->this.driver.getInfo())
        .thenRun(() -> driver.instalarDrivers());

    }//GEN-LAST:event_gplayActionPerformed

    private void gplayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gplayMouseEntered
        // TODO add your handling code here:
        this.gplay.setToolTipText("Configura e instalar Google Play Store.");
    }//GEN-LAST:event_gplayMouseEntered

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        this.jProgressBar1.setValue(30);
        this.console.append("Buscando dispositivo... \n");

        CompletableFuture.runAsync(() -> {
            InfoEntity localvarable = FireTools.this.driver.getInfo();
            if (localvarable != null) {
                FireTools.this.console.append("Encontrado 😎 \n");
                FireTools.this.console.append("Leyendo informaciones   \t: \n");
                FireTools.this.console.append("-Nombre                 \t: " + localvarable.getName() + "\n");
                FireTools.this.console.append("-Modelo                 \t: " + localvarable.getModelo() + "\n");
                FireTools.this.console.append("-Fabricante             \t: " + localvarable.getManufacture() + "\n");
                FireTools.this.console.append("-Systema Operativo      \t: " + localvarable.getOsName() + "\n");
                FireTools.this.console.append("-Parche de Seguridad    \t: "+ localvarable.getSecurity_patch() + "\n");
                FireTools.this.console.append("-Version Android       \t: "+ localvarable.getVersion()+ "\n");
                FireTools.this.console.append("-Version SDK            \t: "+ localvarable.getSdk()+ "\n");
                FireTools.this.console.append("-Tipo de Sistema        \t: "+localvarable.getSystemType()+ "\n");
                FireTools.this.console.append("-Procesador            \t: "+localvarable.getProcesador()+ "\n");
                FireTools.this.jProgressBar1.setValue(100);
                try {
                    Thread.sleep(500);

                } catch (InterruptedException ex) {
                    Logger.getLogger(FireTools.class.getName()).log(Level.SEVERE, null, ex);
                }
                FireTools.this.jProgressBar1.setValue(0);
                return;
            }
            FireTools.this.console.append("No se encontro dispositivo!");
        });

    }//GEN-LAST:event_infoActionPerformed

    private void infoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseEntered
        // TODO add your handling code here:
        this.info.setToolTipText("Leer informacion del equipo.");
    }//GEN-LAST:event_infoMouseEntered

    private void pasosDepuracion(){
            this.console.append("""
                            Para conectar : 
                            1. Ajustes. 
                            2. Acerca del tablet Fire. 
                            3. tap 3 veces sobre "Numero de serie" hasta que aparesca habilitar modo depuracion. 
                            4. un paso a tras. 
                            5. Opciones para desarrolladores. 
                            6. habilita "Depuracion por USB". tap Ok. 
                            7. te saldra una ventana : Permitir depuracion USB? 
                            8. check sobre : Permitir siempre desde este equipo. 
                            9. tap ok
                            .............................................                            
                            """);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FireTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FireTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FireTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FireTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              

                 FireTools sc = new  FireTools();
                 sc.setTitle("FireTool for amazon tablets | v0.1");
                 sc. setSize(800, 500);
               
                 sc.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea console;
    private javax.swing.JPanel consolepanel;
    private javax.swing.JButton gplay;
    private javax.swing.JButton info;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton social_apps;
    private javax.swing.JButton uninstall_G;
    // End of variables declaration//GEN-END:variables
}
