/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package firetools;

import clone.InfoEntity;
import clone.LogicaDrivers;
import clone.LogicaDriversInterfaz;
import java.util.concurrent.CompletableFuture;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author elcue
 */
public class MainScreen extends javax.swing.JFrame {
    //private final AdbManagement adb;
    /**
     * Creates new form MainScreen
     */
     private final LogicaDrivers driver;
    public MainScreen() {
        //adb = new AdbManagment();
        
        initComponents();
        pasosDepuracion();
        driver = new LogicaDriversInterfaz(jProgressBar1, console);
      
        jProgressBar1.setMinimum(0);
        jProgressBar1.setMaximum(100);
        jProgressBar1.setValue(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        mainPanel = new javax.swing.JPanel();
        consolepanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();
        info = new javax.swing.JButton();
        gplay = new javax.swing.JButton();
        social_apps = new javax.swing.JButton();
        info3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(253, 169, 30));

        consolepanel.setBackground(new java.awt.Color(102, 102, 102));

        console.setBackground(new java.awt.Color(204, 204, 204));
        console.setColumns(20);
        console.setRows(5);
        jScrollPane1.setViewportView(console);

        javax.swing.GroupLayout consolepanelLayout = new javax.swing.GroupLayout(consolepanel);
        consolepanel.setLayout(consolepanelLayout);
        consolepanelLayout.setHorizontalGroup(
            consolepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );
        consolepanelLayout.setVerticalGroup(
            consolepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        info.setBackground(new java.awt.Color(26, 12, 90));
        info.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        info.setForeground(new java.awt.Color(255, 255, 255));
        info.setText("Info");
        info.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(51, 255, 255), new java.awt.Color(255, 102, 255), new java.awt.Color(204, 255, 0)));
        info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });

        gplay.setBackground(new java.awt.Color(26, 12, 90));
        gplay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gplay.setForeground(new java.awt.Color(255, 255, 255));
        gplay.setText("GPlay Store");
        gplay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(51, 255, 255), new java.awt.Color(255, 102, 255), new java.awt.Color(204, 255, 0)));
        gplay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gplayActionPerformed(evt);
            }
        });

        social_apps.setBackground(new java.awt.Color(26, 12, 90));
        social_apps.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        social_apps.setForeground(new java.awt.Color(255, 255, 255));
        social_apps.setText("Social Apps");
        social_apps.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(51, 255, 255), new java.awt.Color(255, 102, 255), new java.awt.Color(204, 255, 0)));
        social_apps.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        social_apps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                social_appsActionPerformed(evt);
            }
        });

        info3.setBackground(new java.awt.Color(26, 12, 90));
        info3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        info3.setForeground(new java.awt.Color(255, 255, 255));
        info3.setText("Uninstall GAPP");
        info3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(51, 255, 255), new java.awt.Color(255, 102, 255), new java.awt.Color(204, 255, 0)));
        info3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        info3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info3ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\elcue\\OneDrive\\Escritorio\\Projectos\\FireTools\\src\\firetools\\resources\\amazonlabel.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("by iCodigo");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(consolepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gplay, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(social_apps, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31))
                                    .addComponent(info3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(64, 64, 64))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gplay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(social_apps, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(consolepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
         this.jProgressBar1.setValue(30);
         this.console.append("Buscando dispositivo... \n");
         
         CompletableFuture.runAsync(() -> {
             InfoEntity localvarable = MainScreen.this.driver.getInfo();
             if (localvarable != null) {
                 MainScreen.this.console.append("Encontrado 😎 \n");
                 MainScreen.this.console.append("Leyendo informaciones   \t: \n");
                 MainScreen.this.console.append("-Nombre                 \t: " + localvarable.getName() + "\n");
                 MainScreen.this.console.append("-Modelo                 \t: " + localvarable.getModelo() + "\n");
                 MainScreen.this.console.append("-Fabricante             \t: " + localvarable.getManufacture() + "\n");
                 MainScreen.this.console.append("-Systema Operativo      \t: " + localvarable.getOsName() + "\n");
                 MainScreen.this.console.append("-Parche de Seguridad    \t: "+ localvarable.getSecurity_patch() + "\n");
                 MainScreen.this.console.append("-Version Android       \t: "+ localvarable.getVersion()+ "\n");
                 MainScreen.this.console.append("-Version SDK            \t: "+ localvarable.getSdk()+ "\n");
                 MainScreen.this.console.append("-Tipo de Sistema        \t: "+localvarable.getSystemType()+ "\n");
                 MainScreen.this.console.append("-Procesador            \t: "+localvarable.getProcesador()+ "\n");
                 MainScreen.this.jProgressBar1.setValue(100);
                 try {
                     Thread.sleep(500);
                     
                 } catch (InterruptedException ex) {
                     Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 MainScreen.this.jProgressBar1.setValue(0);
                 return;
             }
              MainScreen.this.console.append("No se encontro dispositivo!");
         });
        
        
           
        
    }//GEN-LAST:event_infoActionPerformed

    private void pasosDepuracion(){
            this.console.append("""
                            Para conectar : 
                            1. Ajustes. 
                            2. Acerca del tablet Fire. 
                            3. tap 3 veces sobre "Numero de serie" hasta que aparesca habilitar modo depuracion. 
                            4. un paso a tras. 
                            5. Opciones para desarrolladores. 
                            6. habilita "Depuracion por USB". tap Ok. 
                            7. te saldra una ventana : Permitir depuracion USB? 
                            8. check sobre : Permitir siempre desde este equipo. 
                            9. tap ok
                            .............................................                            
                            """);
    }
    private void gplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gplayActionPerformed
         // TODO add your handling code here:
         this.jProgressBar1.setValue(30);
         this.console.append("Buscando dispositivo...");
         CompletableFuture.runAsync(() ->this.driver.getInfo())
         .thenRun(() -> driver.instalarDrivers());
        
    }//GEN-LAST:event_gplayActionPerformed

    private void social_appsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_social_appsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_social_appsActionPerformed

    private void info3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea console;
    private javax.swing.JPanel consolepanel;
    private javax.swing.JButton gplay;
    private javax.swing.JButton info;
    private javax.swing.JButton info3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton social_apps;
    // End of variables declaration//GEN-END:variables
}
